Sm/sfCommand
salesforcecli/plugin-templates pull request #22
Opened 2023-02-03 17:21 UTC by mshanemc

> requires https://github.com/forcedotcom/salesforcedx-templates/pull/543 to correct some type inconsistency

> these are still the old names (and mostly the old messages).  They'll be moved in the next round

### What does this PR do?
migrate to sfCommand
change all FS-driven UT to NUTs
mostly use Types correctly (salesforcedx-templates is loose with how it calls yeoman and there's not much to be done from the plugin)

### What issues does this PR fix or reference?
@W-11976561@

2023-02-03 21:54 UTC, peternhale requested changes
I don't see schemas for command return types.

2023-02-03 21:54 UTC, peternhale commented on package.json
> +    "@salesforce/sf-plugins-core": "^2.0.0-beta.8",
@mshanemc change to `^2.0.1`

2023-02-06 18:19 UTC, mshanemc commented on messages/messages.md
> +See more help with --help
oh, yeah, I forgot I changed the tests so that they weren't asserting oclif flag errors.

2023-02-06 21:24 UTC, peternhale requested changes

2023-02-06 21:24 UTC, peternhale commented on package.json
>      "@salesforce/command": "^5.2.1",
Should be able to remove @salesforce/command

2023-02-07 12:37 UTC, peternhale approved these changes
@mshanemc are you going to make a pass at switch command and flag names in the tests?

2023-02-09 18:27 UTC, merged